name: WarpManager
version: '${project.version}'
main: me.seven.reintmase.warpmanager.Main
api-version: '1.20'
depend:
  - Vault
commands:
  addwarp:
    description: Adds warps
    usage: /addwarp
  remwarp:
    description: Removes warps
    usage: /remwarp
  visit:
    description: Visits warps
    usage: /visit
  warp:
    description: Warps commands
    usage: /warp
  warps:
    description: Warps menu
    usage: /warps
  wm:
    description: Admin commands
    usage: /wm
permissions:
  wm.admin:
    description: For use admin commands
